name: "KiBot"

on:
  push:
    paths:
      - "**/*"
      - '**/*.kicad*'
      - '**/*.kibot.yaml'
    tags:
      - '*'

    # Will this cause tags to not work also??
    branches-ignore:
      - 'master'
      - 'main'
      
jobs:
  test:
    uses: pettym/kicad-build-system/.github/workflows/kibot-ci.yml@build-system
