name: "foobar"

on:
  push:
    paths:
      - "**/*"
      - '**/*.kicad*'
      - '**/*.kibot.yaml'
    tags:
      - '*'
    branches-ignore:
      - 'master'
      - 'main'

jobs:
  test:
    uses: pettym/kicad-build-system/.github/workflows/kicad.yaml@build-system
